services:
  remnawave-tg-shop:
    #image: ghcr.io/machka-pasla/remnawave-tg-shop:latest
    build: .
    container_name: remnawave-tg-shop
    hostname: remnawave-tg-shop
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - remnawave-network
    volumes:
      - ./locales:/app/locales
    restart: unless-stopped

  remnawave-tg-shop-db:
    image: postgres:17
    container_name: remnawave-tg-shop-db
    hostname: remnawave-tg-shop-db
    env_file:
      - .env
    volumes:
      - remnawave-tg-shop-db-data:/var/lib/postgresql/data
    networks:
      - remnawave-network
    restart: unless-stopped

networks:
  remnawave-network:
    external: true

volumes:
  remnawave-tg-shop-db-data:
    name: remnawave-tg-shop-db-data
